version: "3.6"

services:
  web:
    image: ${IMAGE_VERSION}
    networks:
    - code-overlay
    env_file:
    - ./dev.env
    deploy:
      replicas: 1
      resources:
        limits: 
          cpus: '0.4'
          memory: 256m
        reservations:
          cpus: '0.2'
          memory: 128m
      restart_policy: 
        condition: on-failure
    logging:
      driver: fluentd
      options:
        tag: dev.nft.web
        fluentd-async-connect: "true"

networks:
  code-overlay:
    external: true
