version: "3.6"

services:
  web:
    image: ${IMAGE_VERSION}
    networks:
    - code-overlay
    env_file:
    - ./prod.env
    deploy:
      replicas: 2
      resources:
        limits: 
          cpus: '0.4'
          memory: 256m
        reservations:
          cpus: '0.2'
          memory: 128m
      placement:
        constraints:
        - node.labels.server == nftnode
      restart_policy: 
        condition: on-failure
    logging:
      driver: fluentd
      options:
        tag: prod.nft.web
        fluentd-async-connect: "true"

networks:
  code-overlay:
    external: true
